# baseURL = "https://sharp-snyder-ac4d75.netlify.app/"
baseURL = "https://kkornalewska.github.io/HugoSite/"
languageCode = "en-us"
title = "Hugo JAMSite"
theme = "tale"
copyright = "2021 - BBR"
# disableKinds = ["section"]

[outputs]
home = ["HTML", "JSON"]
