### Local repository configuration:
#backend:
#  name: git-gateway
#  branch: master # Branch to update (optional; defaults to master)

### GitHub repository configuration:
backend:
  name: github
  repo: kkornalewska/HugoSite  # Path to your GitHub repository

local_backend: true

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "page"
    label: "Page"
    folder: "content/CMS/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Katarzyna Kornalewska", "Jan Kowalski", "Anna Nowak"]}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "premium"
    label: "Premium Page"
    folder: "content/CMS/premium"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Katarzyna Kornalewska", "Jan Kowalski", "Anna Nowak"]}
      - {label: "Date", name: "date", widget: "date"}
